### PR TITLE
[OPS-7237] update base image to be used

### PR DESCRIPTION
**Pull request by teodorescuserban**
NodeJS 12.20.1 (latest security patch).

### CODE REVIEW

**Review by s0 — APPROVED** [review]

**Comment by s0** [comment]
@Pandya-Hardik we need to figure out how to correctly test this, and deploy it. I believe only I have access to run the deployments to chrome headless. Is this FTS of HumInsight that uses chrome headless instead of snap? We should then determine which environments we can deploy to to test this before updating the production chrome headless.

**Comment by teodorescuserban** [comment]
ping @Pandya-Hardik

**Comment by teodorescuserban** [comment]
ping @emmajane @s0 @Pandya-Hardik 
this is now changed again due to jan security releases. Please review and merge. Thank you.

**Comment by emmajane** [comment]
Bump for @s0 and @berliner to prioritise.

**Comment by berliner** [comment]
@s0 Insights uses this. Best to test is demo I'd say.

**Review by berliner — APPROVED** [review]
Looks sensible to me.

**Pull request merged**
